### ISSUE TITLE
No transition = "none" option

### ISSUE THREAD

**Issue by AloeDream** [MohammadYounes/AlertifyJS#101]
Need to disable any animation of confirm dialog. Tried to set transition empty or equal to none, undefined, etc, but not helping. How do I completely turn transitions off?

**Comment by MohammadYounes** [comment]
The animation is CSS based, setting the transition to null or empty will disable the dialog animation but the modal/dimmer opacity transition will remain active. To completely turn it off, you need to include the the following CSS override:

```css
.alertify .ajs-dimmer, .alertify .ajs-modal  { transition: none; }
```
