### ISSUE TITLE
Popup defaultFocus speed

### ISSUE THREAD

**Issue by seltix5** [MohammadYounes/AlertifyJS#150]
Hi,
When oppening a popup there is a delay between the click and the defaultFocus button to be focused, in a batch work it is not possible to do a quick [click] -> [enter] action because of the delay, resulting on a 2 button press (one by click and the second by enter press on the samme button).

Is there a way to reduce this delay?

thank you!

**Comment by MohammadYounes** [comment]
Hi,

This is due to [waiting](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/dialog/dialog.js#L278-L285) for the animation to end, and then the [focus is set](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/js/dialog/transition.js#L13). You can reduce this by decreasing the [In/Out animation duration](https://github.com/MohammadYounes/AlertifyJS/blob/master/src/less/alertify.less#L447-L458). For example:
```css
.alertify.ajs-in:not(.ajs-hidden) .ajs-dialog,
.alertify.ajs-out.ajs-hidden .ajs-dialog {
     animation-duration: 150ms;
}
```
Thanks.
