### ISSUE TITLE
Automatic wrapping on long words

### ISSUE THREAD

**Issue by WouterVanherck** [MohammadYounes/AlertifyJS#191]
I'm wondering if there're any plans for automatic wrapping of long words or a way of extending the area?

In my case, I'm printing out an exception which might contain a path. The sentence shown will go out of bounds. Since I'm printing an exception, I can't just split the long words myself.

**Comment by MohammadYounes** [comment]
This is all controllable via CSS, I left it for the developer on a case by case basis. For example:

**Force word break in notifications:**
* CSS
```css
.alertify-notifier.ajs-right  .ajs-message.ajs-custom.ajs-visible {
    right: 0;
    transform: translateX(-100%);
}
.ajs-message.ajs-custom {
     width: calc(100vw - 70px);
     overflow-wrap:break-word;
     word-wrap: break-word;
     color: #31708f; 
     background-color: #d9edf7;
     border-color: #31708f; 
}
```
* JS
```js
alertify.notify(`Path: /c/user/bin/very/long/long/path/that/might/go/out/of/screen/c/user/bin/very/long/long/path/that/might/go/out/of/screen/c/user/bin/very/long/long/path/that/might/go/out/of/screen`,'custom', 50)
```


**Force word break in dialogs**

* CSS
```css
.ajs-content {
    overflow-wrap:break-word;
    word-wrap: break-word;
}
```
  * JS
```js
alertify.alert(`Path: /c/user/bin/very/long/long/path/that/might/go/out/of/screen/c/user/bin/very/long/long/path/that/might/go/out/of/screen/c/user/bin/very/long/long/path/that/might/go/out/of/screen`)
```
