### ISSUE TITLE
disable dismiss on click

### ISSUE THREAD

**Issue by fcastell** [MohammadYounes/AlertifyJS#198]
is it possible to disable the dismiss on click in settings?

**Comment by fcastell** [comment]
I found a workaround:
Inside javascript:
```javascript
alertify.defaults.notifier.closeButton = true;
```

And in css:
```css
.ajs-close {
    visibility: hidden;
}
```
