### ISSUE TITLE
Notifier animation

### ISSUE THREAD

**Issue by Hamatek** [MohammadYounes/AlertifyJS#37]
Hello, 
I was wondering if there is a way to change notifier animation, like this 
 alertify.set 'notifier', position:'top-left',transition:'pulse'

the default one doesn't work well on android phoneGap it looks laggy.

Cheers

**Comment by MohammadYounes** [comment]
Currently, the `notifier` uses a fixed transition and there is no such option.

I'm unable to test this, it would be great if you could try the following and let me know if you get a smoother transition:

  1. Add `translate3d(0, 0, 0);` to the message (forcing hardware acceleration):

    ```CSS
    .alertify-notifier .ajs-message {
     -webkit-transform: translate3d(0, 0, 0);
             transform: translate3d(0, 0, 0);
    }
    ```
  2. **OR** Decrease the transition duration ([codepen](http://codepen.io/anon/pen/QwYGgV)):

    ```CSS
    .alertify-notifier .ajs-message {
      -webkit-transition-duration: 125ms;
              transition-duration: 125ms;
    }
    .alertify-notifier .ajs-message.ajs-visible {
      -webkit-transition-duration: 250ms;
              transition-duration: 250ms;
    }
    ```

  3. **OR** Use one of the dialog animations ([codepen](http://codepen.io/anon/pen/MYLboR)):

    ```CSS
    .alertify-notifier .ajs-message.ajs-visible {
      -webkit-animation-name: ajs-pulseIn;
              animation-name: ajs-pulseIn;
      -webkit-animation-duration: 500ms;
              animation-duration: 500ms;
      -webkit-transition:none;
              transition:none;
    }
    ```

Thanks.
