### ISSUE TITLE
request large size option like bs3?

### ISSUE THREAD

**Issue by yuomtheara** [MohammadYounes/AlertifyJS#47]
Alertifyjs have the small, and full screen.
But I would like to request the large size like bs3.

**Comment by MohammadYounes** [comment]
You can get any size you want by means of CSS:

```css
.alertify .ajs-dialog  {
  max-width: 300px;
}
.alertify.ajs-resizable:not(.ajs-maximized) .ajs-dialog{
  min-width: 348px;
}
```

Does this work for you ?

**Comment by yuomtheara** [comment]
I can do this with fix screen size, but I want to calculate with screen size (auto)?

**Comment by MohammadYounes** [comment]
Use percentages:

```css
.alertify .ajs-dialog  {
  max-width: 30%;
}
.alertify.ajs-resizable:not(.ajs-maximized) .ajs-dialog{
  min-width: 30%;
}
```
