### ISSUE TITLE
Increasing resize handle

### ISSUE THREAD

**Issue by trokster** [MohammadYounes/AlertifyJS#48]
Hi there,

Tried myself but not happy with results. What is the easiest way of increasing the resize handle on a dialog ? It's a tad too small for tablets and phones.

Thanks :)

**Comment by MohammadYounes** [comment]
I would customize its CSS  :)

```css
/* increase resize handle size*/
.alertify .ajs-handle {
  width: 20px;
  height: 20px;
  background-repeat: no-repeat;
  background-position: bottom right;
}
/* increase right padding to prevent last action button from overlapping with resize handle*/
.alertify .ajs-footer {
  padding-right:20px;
}
```
Try it and let me know!
